# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(588, 433)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 131, 241))
        self.groupBox.setObjectName("groupBox")
        self.lamp_button_8 = QtWidgets.QPushButton(self.groupBox)
        self.lamp_button_8.setGeometry(QtCore.QRect(60, 180, 51, 51))
        self.lamp_button_8.setObjectName("lamp_button_8")
        self.lamp_button_3 = QtWidgets.QPushButton(self.groupBox)
        self.lamp_button_3.setGeometry(QtCore.QRect(10, 130, 51, 51))
        self.lamp_button_3.setObjectName("lamp_button_3")
        self.lamp_button_6 = QtWidgets.QPushButton(self.groupBox)
        self.lamp_button_6.setGeometry(QtCore.QRect(60, 80, 51, 51))
        self.lamp_button_6.setObjectName("lamp_button_6")
        self.lamp1_button = QtWidgets.QPushButton(self.groupBox)
        self.lamp1_button.setGeometry(QtCore.QRect(10, 30, 51, 51))
        self.lamp1_button.setObjectName("lamp1_button")
        self.lamp_button_4 = QtWidgets.QPushButton(self.groupBox)
        self.lamp_button_4.setGeometry(QtCore.QRect(10, 180, 51, 51))
        self.lamp_button_4.setObjectName("lamp_button_4")
        self.lamp_button_5 = QtWidgets.QPushButton(self.groupBox)
        self.lamp_button_5.setGeometry(QtCore.QRect(60, 30, 51, 51))
        self.lamp_button_5.setObjectName("lamp_button_5")
        self.lamp_button_2 = QtWidgets.QPushButton(self.groupBox)
        self.lamp_button_2.setGeometry(QtCore.QRect(10, 80, 51, 51))
        self.lamp_button_2.setObjectName("lamp_button_2")
        self.lamp_button_7 = QtWidgets.QPushButton(self.groupBox)
        self.lamp_button_7.setGeometry(QtCore.QRect(60, 130, 51, 51))
        self.lamp_button_7.setObjectName("lamp_button_7")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 280, 120, 80))
        self.groupBox_2.setObjectName("groupBox_2")
        self.port_comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.port_comboBox.setGeometry(QtCore.QRect(10, 50, 101, 27))
        self.port_comboBox.setObjectName("port_comboBox")
        self.commButton = QtWidgets.QPushButton(self.groupBox_2)
        self.commButton.setGeometry(QtCore.QRect(10, 20, 101, 27))
        self.commButton.setObjectName("commButton")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(140, 20, 381, 221))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(10, 30, 67, 17))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 67, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 67, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 67, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(10, 150, 67, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(10, 180, 67, 17))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(210, 30, 67, 17))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(210, 60, 67, 17))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(210, 90, 67, 17))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(210, 120, 67, 17))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(210, 180, 67, 17))
        self.label_11.setObjectName("label_11")
        self.lcdMag_1 = QtWidgets.QLCDNumber(self.groupBox_3)
        self.lcdMag_1.setGeometry(QtCore.QRect(80, 30, 64, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 160, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.lcdMag_1.setPalette(palette)
        self.lcdMag_1.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdMag_1.setObjectName("lcdMag_1")
        self.lcdMag_2 = QtWidgets.QLCDNumber(self.groupBox_3)
        self.lcdMag_2.setGeometry(QtCore.QRect(80, 60, 64, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 160, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.lcdMag_2.setPalette(palette)
        self.lcdMag_2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdMag_2.setObjectName("lcdMag_2")
        self.lcdMag_3 = QtWidgets.QLCDNumber(self.groupBox_3)
        self.lcdMag_3.setGeometry(QtCore.QRect(80, 90, 64, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 160, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.lcdMag_3.setPalette(palette)
        self.lcdMag_3.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdMag_3.setObjectName("lcdMag_3")
        self.lcdMag_4 = QtWidgets.QLCDNumber(self.groupBox_3)
        self.lcdMag_4.setGeometry(QtCore.QRect(80, 120, 64, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 160, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.lcdMag_4.setPalette(palette)
        self.lcdMag_4.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdMag_4.setObjectName("lcdMag_4")
        self.lcdMag_5 = QtWidgets.QLCDNumber(self.groupBox_3)
        self.lcdMag_5.setGeometry(QtCore.QRect(80, 150, 64, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 160, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.lcdMag_5.setPalette(palette)
        self.lcdMag_5.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdMag_5.setObjectName("lcdMag_5")
        self.lcdMag_6 = QtWidgets.QLCDNumber(self.groupBox_3)
        self.lcdMag_6.setGeometry(QtCore.QRect(80, 180, 64, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 160, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.lcdMag_6.setPalette(palette)
        self.lcdMag_6.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdMag_6.setObjectName("lcdMag_6")
        self.lcdPir_1 = QtWidgets.QLCDNumber(self.groupBox_3)
        self.lcdPir_1.setGeometry(QtCore.QRect(280, 30, 64, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 160, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.lcdPir_1.setPalette(palette)
        self.lcdPir_1.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdPir_1.setObjectName("lcdPir_1")
        self.lcdPir_2 = QtWidgets.QLCDNumber(self.groupBox_3)
        self.lcdPir_2.setGeometry(QtCore.QRect(280, 60, 64, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 160, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.lcdPir_2.setPalette(palette)
        self.lcdPir_2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdPir_2.setObjectName("lcdPir_2")
        self.lcdPir_3 = QtWidgets.QLCDNumber(self.groupBox_3)
        self.lcdPir_3.setGeometry(QtCore.QRect(280, 90, 64, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 160, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.lcdPir_3.setPalette(palette)
        self.lcdPir_3.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdPir_3.setObjectName("lcdPir_3")
        self.lcdPir_4 = QtWidgets.QLCDNumber(self.groupBox_3)
        self.lcdPir_4.setGeometry(QtCore.QRect(280, 120, 64, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 160, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.lcdPir_4.setPalette(palette)
        self.lcdPir_4.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdPir_4.setObjectName("lcdPir_4")
        self.lcdDeadman = QtWidgets.QLCDNumber(self.groupBox_3)
        self.lcdDeadman.setGeometry(QtCore.QRect(280, 180, 64, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 160, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.lcdDeadman.setPalette(palette)
        self.lcdDeadman.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdDeadman.setObjectName("lcdDeadman")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 588, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Lamparas"))
        self.lamp_button_8.setText(_translate("MainWindow", "L8"))
        self.lamp_button_3.setText(_translate("MainWindow", "L3"))
        self.lamp_button_6.setText(_translate("MainWindow", "L6"))
        self.lamp1_button.setText(_translate("MainWindow", "L1"))
        self.lamp_button_4.setText(_translate("MainWindow", "L4"))
        self.lamp_button_5.setText(_translate("MainWindow", "L5"))
        self.lamp_button_2.setText(_translate("MainWindow", "L2"))
        self.lamp_button_7.setText(_translate("MainWindow", "L7"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Puerto Serie"))
        self.commButton.setText(_translate("MainWindow", "Conectar"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Sensores "))
        self.label.setText(_translate("MainWindow", "Mag1"))
        self.label_2.setText(_translate("MainWindow", "Mag2"))
        self.label_3.setText(_translate("MainWindow", "Mag3"))
        self.label_4.setText(_translate("MainWindow", "Mag4"))
        self.label_5.setText(_translate("MainWindow", "Mag5"))
        self.label_6.setText(_translate("MainWindow", "Mag6"))
        self.label_7.setText(_translate("MainWindow", "PIR1"))
        self.label_8.setText(_translate("MainWindow", "PIR2"))
        self.label_9.setText(_translate("MainWindow", "PIR3"))
        self.label_10.setText(_translate("MainWindow", "PIR4"))
        self.label_11.setText(_translate("MainWindow", "Deadman"))

